import test from 'node:test'; import assert from 'node:assert/strict';
import {AdcZeroDowntimeAdapter,buildAdcTopology,buildCompatibilityGate,buildSessionSafetyGate,buildMigrationCheckpoints,buildTrafficSwitchPlan,buildRollbackPlan,buildAdcReadinessGate,buildAdcZeroDowntimeAssessment} from '../src/index.js';
const project={id:'project:phase10',name:'R16 to R25 ADC',sourceRelease:'R16',targetRelease:'R25'};
function readyInputs(){const topology=buildAdcTopology({project,active:{id:'adc-a',status:'HEALTHY'},standby:{id:'adc-b',status:'HEALTHY'},healthChecks:[{id:'standby-health',status:'PASSED'}],sessions:{count:20,drained:true}});const compatibilityGate=buildCompatibilityGate({activeRelease:'R16',standbyRelease:'R25',targetRelease:'R25',dualRunReady:true,checks:[{id:'api',status:'PASSED'}]});const sessionSafetyGate=buildSessionSafetyGate({activeSessions:20,drainRequired:true,drainReady:true,stickySessionsSafe:true,inFlightTransactions:0,transactionsSafe:true});const checkpoints=buildMigrationCheckpoints([{id:'migration-complete',status:'PASSED',evidenceIds:['e1']}]);return{topology,compatibilityGate,sessionSafetyGate,checkpoints};}
test('Phase 10 builds active/standby topology and health model',()=>{const {topology}=readyInputs();assert.equal(topology.type,'ADC_TOPOLOGY');assert.equal(topology.ready,true);});
test('Phase 10 blocks incompatible standby',()=>{assert.equal(buildCompatibilityGate({activeRelease:'R16',standbyRelease:'R16',targetRelease:'R25'}).status,'BLOCKED');assert.equal(buildCompatibilityGate({activeRelease:'R16',standbyRelease:'R25',targetRelease:'R25',dualRunReady:true}).status,'READY');});
test('Phase 10 requires session and transaction safety',()=>{assert.equal(buildSessionSafetyGate({drainRequired:true,drainReady:false,stickySessionsSafe:true,inFlightTransactions:1,transactionsSafe:false}).status,'BLOCKED');assert.equal(buildSessionSafetyGate({drainRequired:true,drainReady:true,stickySessionsSafe:true,inFlightTransactions:0,transactionsSafe:true}).status,'READY');});
test('Phase 10 creates controlled traffic switch plan',()=>{const i=readyInputs();const p=buildTrafficSwitchPlan(i);assert.equal(p.status,'SWITCH_READY');assert.equal(p.humanApprovalRequired,true);});
test('Phase 10 requires rollback readiness',()=>{assert.equal(buildRollbackPlan({previousActiveId:'a',standbyId:'b',trafficReversalReady:false,dataRollbackReady:true}).status,'BLOCKED');assert.equal(buildRollbackPlan({previousActiveId:'a',standbyId:'b',trafficReversalReady:true,dataRollbackReady:true,healthChecks:[{status:'PASSED'}]}).status,'READY');});
test('Phase 10 gate requires human approval',()=>{const i=readyInputs();const p=buildTrafficSwitchPlan(i);const r=buildRollbackPlan({previousActiveId:'adc-a',standbyId:'adc-b',trafficReversalReady:true,dataRollbackReady:true,healthChecks:[{status:'PASSED'}]});assert.equal(buildAdcReadinessGate({...i,trafficPlan:p,rollbackPlan:r,healthStatus:'PASSED',approvalStatus:'PENDING'}).status,'BLOCKED');assert.equal(buildAdcReadinessGate({...i,trafficPlan:p,rollbackPlan:r,healthStatus:'PASSED',approvalStatus:'APPROVED'}).status,'READY');});
test('Phase 10 assessment is explicitly non-autonomous',()=>{const i=readyInputs(),p=buildTrafficSwitchPlan(i),r=buildRollbackPlan({previousActiveId:'a',standbyId:'b',trafficReversalReady:true,dataRollbackReady:true,healthChecks:[{status:'PASSED'}]}),g=buildAdcReadinessGate({...i,trafficPlan:p,rollbackPlan:r,healthStatus:'PASSED',approvalStatus:'APPROVED'}),a=buildAdcZeroDowntimeAssessment({project,...i,trafficPlan:p,rollbackPlan:r,readinessGate:g,evidence:[{id:'e1'}]});assert.equal(a.status,'READY');assert.equal(a.safety.autonomousTrafficSwitch,false);});
test('Phase 10 adapter exposes ADC contract',()=>{assert.deepEqual(new AdcZeroDowntimeAdapter().capabilities(),['buildTopology','buildCompatibilityGate','buildSessionSafetyGate','buildMigrationCheckpoints','buildTrafficSwitchPlan','buildRollbackPlan','buildReadinessGate','buildAssessment']);});