import test from 'node:test';import assert from 'node:assert/strict';import {ingestOperationResult,evaluateLiveTelemetry,evaluateIncidentPolicy,appendAuditEntry,verifyAuditChain,reconcileCutover,buildLiveCutoverAssessment,buildLiveCutoverSurface} from '../src/index.js';
const project={id:'project:phase13',name:'Live Cutover',sourceRelease:'R16',targetRelease:'R25'};
test('Phase 13 ingests external operation results without executing',()=>{const r=ingestOperationResult({project,operationId:'op-1',action:'ADC_SWITCH',status:'SUCCEEDED',sourceSystem:'adc'});assert.equal(r.type,'LIVE_OPERATION_RESULT');assert.equal(r.status,'SUCCEEDED');assert.equal(r.autonomousExecution,false);});
test('Phase 13 evaluates live telemetry and thresholds',()=>{assert.equal(evaluateLiveTelemetry({health:{status:'HEALTHY'},adc:{status:'HEALTHY'},runtime:{status:'HEALTHY',errorRate:0.1},thresholds:{maxErrorRate:0.5}}).status,'HEALTHY');assert.equal(evaluateLiveTelemetry({health:{status:'HEALTHY'},adc:{status:'DEGRADED'},runtime:{status:'HEALTHY'}}).status,'DEGRADED');});
test('Phase 13 triggers incident and recommends rollback without executing it',()=>{const r=evaluateIncidentPolicy({operationResults:[{operationId:'op-1',status:'FAILED'}],telemetry:{status:'HEALTHY'}});assert.equal(r.status,'INCIDENT');assert.equal(r.rollbackRecommended,true);assert.equal(r.autonomousRollback,false);});
test('Phase 13 maintains a verifiable audit hash chain',()=>{const a=appendAuditEntry({eventType:'CUTOVER_START',event:{stage:'drain'},actor:'operator'});const b=appendAuditEntry({audit:[a],eventType:'ADC_SWITCH',event:{operationId:'op-1'},actor:'operator'});assert.equal(verifyAuditChain([a,b]).valid,true);assert.equal(verifyAuditChain([a,{...b,event:{operationId:'tampered'}}]).valid,false);});
test('Phase 13 reconciles expected operations and post-cutover health',()=>{const r=reconcileCutover({expectedOperations:['op-1'],operationResults:[{operationId:'op-1',status:'SUCCEEDED'}],postCutover:{status:'HEALTHY'}});assert.equal(r.status,'RECONCILED');});
test('Phase 13 blocks incomplete reconciliation',()=>{const r=reconcileCutover({expectedOperations:['op-1','op-2'],operationResults:[{operationId:'op-1',status:'SUCCEEDED'}],postCutover:{status:'HEALTHY'}});assert.equal(r.status,'INCOMPLETE');});
test('Phase 13 builds a non-autonomous T24Tools live cutover surface',()=>{const s=buildLiveCutoverSurface({project,controlTower:{status:'READY_FOR_APPROVAL'}});assert.equal(s.type,'LIVE_CUTOVER_EVIDENCE');assert.equal(s.safety.autonomousRollback,false);});
