import test from 'node:test';import assert from 'node:assert/strict';import {OperationsExecutionAdapter,buildOperationRequest,buildOperationEvidence,buildOperationsSurface} from '../src/index.js';
const project={id:'project:phase12',name:'Operations',sourceRelease:'R16',targetRelease:'R25'};
test('Phase 12 exposes external operation contracts',()=>{assert.deepEqual(new OperationsExecutionAdapter().capabilities(),['healthCheck','validateMigration','collectRuntimeLogs','deploy','rollback','drainAdcTraffic','switchAdcTraffic','rollbackAdcTraffic']);});
test('Phase 12 defaults to approval-required dry execution',async()=>{const a=new OperationsExecutionAdapter();const r=await a.switchAdcTraffic({adc:'adc-b'});assert.equal(r.status,'APPROVAL_REQUIRED');assert.equal(r.executed,false);});
test('Phase 12 blocks operations without final approval',()=>{const r=buildOperationRequest({action:'ADC_SWITCH',controlTowerStatus:'READY_FOR_APPROVAL',approvalStatus:'PENDING',preconditions:[{id:'health',status:'PASSED'}]});assert.equal(r.status,'BLOCKED');assert.equal(r.authorized,false);});
test('Phase 12 authorizes only approved, ready external execution',()=>{const r=buildOperationRequest({action:'ADC_SWITCH',controlTowerStatus:'READY_FOR_APPROVAL',approvalStatus:'APPROVED',preconditions:[{id:'health',status:'PASSED'},{id:'rollback',status:'READY'}]});assert.equal(r.status,'READY');assert.equal(r.authorized,true);assert.equal(r.autonomousExecution,false);});
test('Phase 12 runner remains an explicit external boundary',async()=>{const calls=[];const a=new OperationsExecutionAdapter({allowExecution:true,runner:async(action,payload)=>{calls.push({action,payload});return{ok:true}}});const r=await a.drainAdcTraffic({timeoutSeconds:30});assert.equal(r.status,'EXECUTED');assert.deepEqual(calls,[{action:'ADC_DRAIN',payload:{timeoutSeconds:30}}]);});
test('Phase 12 captures operation evidence',()=>{const e=buildOperationEvidence({project,operation:{type:'EXTERNAL_OPERATION_REQUEST',action:'ADC_SWITCH'},result:{status:'EXECUTED',executed:true}});assert.equal(e.sourceType,'EXTERNAL_OPERATION');assert.equal(e.release,'R25');});
test('Phase 12 T24Tools operations surface is non-autonomous',()=>{const s=buildOperationsSurface({project,controlTower:{status:'READY_FOR_APPROVAL'},operations:[]});assert.equal(s.type,'OPERATIONS_INTEGRATION');assert.equal(s.safety.autonomousExecution,false);});
