import test from 'node:test';
import assert from 'node:assert/strict';
import {DagOrchestrator,createUpgradeAssessmentDag} from '../src/orchestration/dag.js';
import {AgenticSuiteAdapter} from '../src/adapters/agentic-suite.js';

test('upgrade DAG exposes parallel discovery stages and an approval gate',()=>{const dag=createUpgradeAssessmentDag();assert.deepEqual(dag.nodes.find(n=>n.id==='repository-inventory').dependsOn,[]);assert.deepEqual(dag.nodes.find(n=>n.id==='release-comparison').dependsOn,[]);assert.equal(dag.nodes.find(n=>n.id==='human-review').approvalGate,true)});
test('orchestrator runs independent nodes in parallel then stops at approval',async()=>{const calls=[];const o=new DagOrchestrator({runner:async({node})=>{calls.push(node.id);return{node:node.id}}});const state=await o.createRun({project:{id:'p1'},workflow:'R16-R25-UPGRADE-ASSESSMENT',nodes:createUpgradeAssessmentDag().nodes});const paused=await o.run(state.run.id);assert.equal(paused.run.status,'WAITING_APPROVAL');assert.deepEqual(new Set(calls),new Set(['repository-inventory','release-comparison','correlation','risk-and-remediation']));await o.approveGate(state.run.id,'human-review',true);const done=await o.resume(state.run.id);assert.equal(done.run.status,'COMPLETED');assert.equal(done.dag.nodes.find(n=>n.id==='verification-and-report').status,'COMPLETED')});
test('agentic-suite adapter is safe without a configured command',async()=>{const adapter=new AgenticSuiteAdapter();const result=await adapter.startRun({runId:'r1',workflow:'test',dag:{nodes:[]},context:{}});assert.equal(result.result.mode,'manifest-only');assert.equal(adapter.getRunState('r1').status,'RUNNING')});
test('agentic-suite adapter forwards commands through injected runner',async()=>{const calls=[];const adapter=new AgenticSuiteAdapter({command:'suite-bridge',runner:async input=>{calls.push(input);return{ok:true}}});await adapter.pauseRun('r2');assert.equal(calls[0].command,'suite-bridge');assert.equal(calls[0].args[0],'pause')});
