import{createArtifact,createDependency,createEvidence}from'../core/contracts.js';
const basename=p=>(p||'').split('/').pop()||p;
const stableId=value=>{let h=2166136261;for(const c of String(value)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return(h>>>0).toString(16)};
function artifactType(f){const ext=f.extension??f.ext??'';const p=String(f.path??'').toLowerCase();if(ext==='.b'||/routine/.test(p))return'ROUTINE';if(ext==='.java')return'JAVA_HOOK';if(ext==='.t24r')return'CONFIG_RECORD';if(/component/.test(p))return'COMPONENT';return'SOURCE_FILE'}
function language(f){return f.language??f.lang??null}
export class RepoMindAdapter{
 constructor(o={}){this.id='repomind';this.version=o.version??'read-only-export-v1';this.transport=o.transport??'export';this.capabilities=['getRepositoryProfile','listArtifacts','findSymbol','findReferences','getDependencies','getDependents','analyzeImpact','getLimitations'];this.index=null}
 loadIndex(index){if(!index||!Array.isArray(index.files))throw new Error('RepoMind export must contain a files array');this.index=index;return this.getRepositoryProfile()}
 healthCheck(){if(!this.index)return{status:'UNVERIFIED',reason:'RepoMind export has not been loaded.'};return{status:'READY',sourceSystem:'RepoMind',fileCount:this.index.files.length,transport:this.transport}}
 getRepositoryProfile(){if(!this.index)throw new Error('RepoMind index is not loaded');return{sourceSystem:'RepoMind',transport:this.transport,projectName:this.index.project?.name??this.index.name??null,fileCount:this.index.files.length,stats:this.index.stats??{},limitations:this.getLimitations()}}
 listArtifacts(filter={}){if(!this.index)throw new Error('RepoMind index is not loaded');return this.index.files.filter(f=>(!filter.extension||(f.extension??f.ext)===filter.extension)&&(!filter.language||language(f)===filter.language))}
 findSymbol(query){if(!this.index)throw new Error('RepoMind index is not loaded');const q=String(query??'').toLowerCase();return(this.index.symbols??[]).filter(s=>String(s.name??'').toLowerCase().includes(q))}
 findReferences(name){if(!this.index)throw new Error('RepoMind index is not loaded');return(this.index.references??[]).filter(r=>String(r.name??'').toLowerCase()===String(name??'').toLowerCase())}
 getDependencies(path){if(!this.index)throw new Error('RepoMind index is not loaded');return(this.index.imports??[]).filter(e=>e.from===path||e.path===path)}
 getDependents(path){if(!this.index)throw new Error('RepoMind index is not loaded');return(this.index.imports??[]).filter(e=>e.to===path||e.module===path)}
 analyzeImpact(node){if(!this.index)throw new Error('RepoMind index is not loaded');const path=typeof node==='string'?node:node?.path;const affected=new Set;for(const e of this.index.imports??[])if(e.to===path||e.module===path)affected.add(e.from??e.path);return{node:path,affected:[...affected],sourceSystem:'RepoMind'}}
 getLimitations(){return this.index?.limitations??['Read-only integration boundary.','Export is authoritative only for what RepoMind successfully indexed.','Dynamic/runtime references may remain unresolved.','No source mutation is performed by the platform.']}
 normalize(projectId,release){if(!this.index)throw new Error('RepoMind index is not loaded');const artifacts=[],dependencies=[],evidence=[],byPath=new Map;for(const f of this.index.files){const id='artifact:'+stableId(f.path);artifacts.push(createArtifact({id,projectId,type:artifactType(f),name:basename(f.path),path:f.path,release,language:language(f),metadata:{lines:f.lines??null,extension:f.extension??f.ext??null},sourceSystem:'RepoMind',externalId:f.path}));byPath.set(f.path,id)}for(const e of this.index.imports??[]){const from=byPath.get(e.from??e.path),to=byPath.get(e.to??e.module);if(from&&to)dependencies.push(createDependency({id:'dependency:'+stableId((e.from??e.path)+'|'+(e.to??e.module)+'|'+(e.line??'')),projectId,fromArtifactId:from,toArtifactId:to,kind:e.kind??'IMPORT',confidence:e.confidence??'high',sourceSystem:'RepoMind'}))}evidence.push(createEvidence({id:'evidence:repomind:'+stableId(JSON.stringify(this.getRepositoryProfile())),sourceSystem:'RepoMind',sourceType:'INDEX',sourceReference:this.index.project?.source??this.index.project?.name??'export',release,toolVersion:this.index.toolVersion??this.version,excerpt:JSON.stringify(this.getRepositoryProfile().stats)}));return{artifacts,dependencies,evidence,limitations:this.getLimitations()}}
}
