export const ARTIFACT_TYPES=Object.freeze(['ROUTINE','INSERT','VERSION','ENQUIRY','SERVICE','JAVA_HOOK','COMPONENT','APPLICATION','FIELD','API','CLASS','CONFIG_RECORD','SOURCE_FILE','OTHER']);
export const SEVERITIES=Object.freeze(['Critical','High','Medium','Low','Informational']);
export const RUN_STATUSES=Object.freeze(['CREATED','RUNNING','WAITING_APPROVAL','COMPLETED','FAILED','CANCELLED']);
const required=(v,n)=>{if(v===undefined||v===null||v==='')throw new Error(n+' is required');return v};
export function createProject(i){return{id:required(i.id,'project.id'),name:required(i.name,'project.name'),sourceRelease:required(i.sourceRelease,'project.sourceRelease'),targetRelease:required(i.targetRelease,'project.targetRelease'),repository:i.repository??null,environment:i.environment??'local',status:i.status??'ACTIVE',createdAt:i.createdAt??new Date().toISOString(),updatedAt:i.updatedAt??new Date().toISOString()}}
export function createRun(i){return{id:required(i.id,'run.id'),projectId:required(i.projectId,'run.projectId'),workflow:required(i.workflow,'run.workflow'),version:i.version??'1.0',status:i.status??'CREATED',startedAt:i.startedAt??null,completedAt:i.completedAt??null,currentStage:i.currentStage??'INTAKE',approvalState:i.approvalState??'NOT_REQUIRED'}}
export function createArtifact(i){return{id:required(i.id,'artifact.id'),projectId:required(i.projectId,'artifact.projectId'),type:ARTIFACT_TYPES.includes(i.type)?i.type:'OTHER',name:required(i.name,'artifact.name'),path:i.path??null,application:i.application??null,release:i.release??null,language:i.language??null,metadata:i.metadata??{},sourceSystem:i.sourceSystem??'unknown',externalId:i.externalId??null}}
export function createDependency(i){return{id:required(i.id,'dependency.id'),projectId:required(i.projectId,'dependency.projectId'),fromArtifactId:required(i.fromArtifactId,'dependency.fromArtifactId'),toArtifactId:required(i.toArtifactId,'dependency.toArtifactId'),kind:i.kind??'REFERENCES',confidence:i.confidence??'unknown',sourceSystem:i.sourceSystem??'unknown'}}
export function createEvidence(i){return{id:required(i.id,'evidence.id'),sourceSystem:required(i.sourceSystem,'evidence.sourceSystem'),sourceType:i.sourceType??'ANALYSIS',sourceReference:i.sourceReference??null,release:i.release??null,contentHash:i.contentHash??null,excerpt:i.excerpt??null,collectedAt:i.collectedAt??new Date().toISOString(),toolVersion:i.toolVersion??null}}
export function createFinding(i){return{id:required(i.id,'finding.id'),projectId:required(i.projectId,'finding.projectId'),artifactId:i.artifactId??null,category:i.category??'GENERAL',severity:SEVERITIES.includes(i.severity)?i.severity:'Informational',status:i.status??'OPEN',title:required(i.title,'finding.title'),description:i.description??'',recommendation:i.recommendation??'',sourceRelease:i.sourceRelease??null,targetRelease:i.targetRelease??null,evidenceIds:i.evidenceIds??[],dependencyIds:i.dependencyIds??[]}}
